#!/usr/bin/env bash
# Bash script that configures an Nginx server so that
# /redirect_me is redirecting to a “301 Moved Permanently” and 404 page.
sudo apt-get -y update
sudo apt-get -y install nginx
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
printf %s "server {
    listen 80;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html index.html index.htm index.nginx-debian.html;

    location /redirect_me {
        return 301 https://www.facebook.com/Abdelilah.bch99;
    }
    error_page 404 /404.html;
    location = /404.html {
            root /var/www/html;
            internal;
    }
}" > /etc/nginx/sites-enabled/default

sudo service nginx restart
